### PR TITLE
Add basic scanner tests

### PR DESCRIPTION
**Pull request by lazorchakp**
I *think* I've done this properly - I added all of the test cases I previously posted to Piazza, with some slight changes (added error messages).

### CODE REVIEW

**Comment by lazorchakp** [comment]
Looks like I should have given my test cases more specific (and snake_case) names (also checked for duplicate files). I'm running low on time to submit, so I'm not going to make these changes now. I'll be contributing test cases in the future!

**Comment by baileyparker** [comment]
Very close! I was just looking at your test cases!

You'll see above that TravisCI failed (click into details to see why). There are some tests that ensure the fixtures are sane. In particular:

    - Fixtures should be `snake_case`
    - `*.sim` files should be unique (in particular, `basic-scanner-test-1.sim` is a duplicate of `all_symbols.sim`)

Here are my suggestions:

  - You can remove `basic-scanner-test-1.sim` (and 12) since `all_symbols.sim` is the same (it appears 11 and 2 are duplicates)
  - Change the fixture names to be snake case and perhaps try giving them more descriptive names so its clear what they are exercising (for example 6 could be `empty_file.{sim,scanner}`)
  - A few of your tests are for undefined parts of the spec or are language specific. I'd recommend removing undefined/language specific parts of those tests
    - `10` is a great test of PROGRAM vs two tokens. However the comment behavior at the end is unspecified. Peter said in class that implementations could either error on an unterminated comment or could ignore it. Remove the comment and this is a great significant white space test
    - 9 appears to be implementation dependent. The assignment says that implementations can impose reasonable limits on the size of integers. Thus, we can't say if `123456789012345678901234567890` should error. I'd just remove that part of the test.

Running the testsuite that ensures this test harness is correct will inform you of some of these problems. You can do so by installing pipenv (`sudo apt install python3-pip && python3 -m install pipenv`) and then running the tests like so `pipenv run python3 setup.py coverage`.

Thanks!

**Comment by baileyparker** [comment]
If I get a chance in the next half hour, I can fix this up and do some git-fu to attribute you as the author.

**Comment by lazorchakp** [comment]
Got it; thanks for the detailed info! Sorry I'm not able to follow up with this immediately - I'm a bit crunched for time. I threw these together pretty haphazardly just so I could be more confident with my submission. Next time I'll spend some more time polishing everything up before submitting a pull request.

**Comment by baileyparker** [comment]
Improved and merged in #7. Thanks for the tests!

**Pull request closed without merging**
